version: 0.0
os: linux
files:
  - source: ./publish/
    destination: /opt/tracker/api/
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: ./clean.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_api.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop_api.sh
      timeout: 300
      runas: root
